### ISSUE TITLE
Only room maker should reveal

### ISSUE THREAD

**Issue by keremcankabadayi** [Zuehlke/poinz#168]
I think there should be an option for revealing permission.

**Comment by xeronimus** [comment]
Hi,  

thanks very much for your suggestion.  Until now, we always refrained from introducing any sort of "permissions" for the users in a room. You might have noticed, that all users in a room can trigger all actions.  Or in other words, the creator is not "distinguished" from the other users.

This is "by design" in order to keep the tool simple. Which we think is the "USP" of PoinZ (compared to other alternatives out there).

We also assume, that the tool is used by a team (you know one another).  We also assume that you could agree on a "custom" / "rule", that only somebody from your team reveals stories... 

But I might be mistaken ;-)  I'd be happy to learn how you use PoinZ!

**Comment by keremcankabadayi** [comment]
okey now, i think we can close this isssue.
