### ISSUE TITLE
Numerical average seems wrong

### ISSUE THREAD

**Issue by deeemmell** [Zuehlke/poinz#179]
![poinz-avg-bug](https://user-images.githubusercontent.com/46517794/113838153-cc14d680-978e-11eb-8488-1e6c39b2d26f.png)

**Comment by xeronimus** [comment]
Thanks for reporting this! 

(5+5+5+4+3) / 5 = 22 / 5 = 4.4

I'll look into this

**Comment by xeronimus** [comment]
@deeemmell ,  can I ask about your Custom Card Configuration... (it seems, you added 4 and 6)...

since the "Label" of the a card can be a non-numerical value (say "?"  or "!"  or "*"), we use the "numerical value" for the calculation of the average.

In the editor, this is the 2nd column.

![image](https://user-images.githubusercontent.com/1777143/113848429-bf957b80-9798-11eb-8645-b1b5dc66df19.png)

Can you confirm, that in your room,  the second column has the integer values 3, 4 and 5 ?

**Comment by deeemmell** [comment]
> Can you confirm, that in your room, the second column has the integer values 3, 4 and 5 ?

Sorry, I never saw the editor -- someone else prepared/edited the cards before our workshop --, so I only ever saw the display values shown on the cards. With your explanations, I now understand how the behavior I observed could come about, and that it's not really a bug but the counter-intuitive result of a strange configuration.

**Comment by xeronimus** [comment]
no worries :)
