### ISSUE TITLE
Round estimations to next great number

### ISSUE THREAD

**Issue by ecaron** [Zuehlke/poinz#207]
Right now the estimation is a pure rounded number (like 3.2). It would be great if the system could control the rounding, defaulting to "nearest greater number" (so showing 5 instead of 3.2).

I'm happy to provide research & prior art from other solutions if that'd help you feel confident in this change.

**Comment by xeronimus** [comment]
Hey @ecaron ,

thanks for the suggestion. To understand more clearly....

in this example below, you would display "Average: 8 (7.67)"   because the "next higher card value" is 8.

![image](https://user-images.githubusercontent.com/1777143/131967281-b8290470-116a-4352-90db-4ca301c81929.png)

In an example, where the numerical average is 6.4  you would display "Average: 5 (6.4)"

**Comment by ecaron** [comment]
If the average is 6.4, I would still round up to 8. This is based on personal experience, as well as these two sources:
* From [Mike Cohn](https://www.mountaingoatsoftware.com/blog/dont-average-during-planning-poker): "if a team truly feels compelled to average, they should take the median (middle value)" 
* From [Luis Gonçalves](https://adaptmethodology.com/planning-poker/): "In my experience, no one ever agrees to a middle ground number and usually chooses the top size at the end of the discussion."

**Comment by xeronimus** [comment]
ok, so let's try to specify this a bit more. So I can write an algorithm:

1. calculate numerical median  (50% of the votes higher, 50% of the votes lower)
2. find the card, where the numerical difference to the calculated median is minimal

or 

2. always take the next higher card ?

**Comment by ecaron** [comment]
I played with a couple different styles of logic (ln, golden ratio, crazier stuff). In the end, I kind of like how this could work in [getEstimationSummary.js](https://github.com/Zuehlke/poinz/blob/master/client/app/components/EstimationArea/getEstimationSummary.js):
```javascript
const consensus = (values) => {
  const avg = average(values);
  if (!avg) return avg;
  const cards = [0.5, 1, 2, 3, 5, 8, 13, 21, 34, 55]
  const approx = avg * .9
  return cards.find(v => v >= approx)
};
```
The `* .9` part is a way of saving "if you're within 10% of the card beneath you, we'll take it - otherwise we're going with the higher card". I've played through a couple dozen scenarios of round for teams of 5, and this comes out with good recommendation for reasonable scenarios (e.g., no algorithm is going to fix a scenario of 4 1s and 1 55).

Thoughts?

**Comment by xeronimus** [comment]
I like the apporach "if you're within 10% of the card beneath you, we'll take it"

But I do not see that represented in the proposed implementation (or I'm just not getting it ;) )

you're saying that "if the difference between the numerical average and the next lower card value is small enough, we'll take it".
"small enough meaning:  less than 10% of the value of that lower card"    ?

so that would mean something like :

`
const consensus = (values) => {
  const avg = average(values);
  if (!avg) return avg;
  const cards = [0.5, 1, 2, 3, 5, 8, 13, 21, 34, 55];   // <<- assume that this is always sorted in ASC order
 
  const lowerCardIndex = cards.findIndex(v => v>= avg);
  const lowerCard = cards[lowerCardIndex];
  const nextCard = cards[lowerCardIndex + 1];
  
  const diff = avg - lowerCard;
  
  return (diff <= 0.1*lowerCard) ? lowerCard : nextCard;
  
};

`

**Comment by ecaron** [comment]
The `const approx = avg * .9;` line of my snippet is doing the work of handling the 10% range.
I started it with `const approx = avg - (.1 * avg)`, and then I realized that's the same as `.9`
The using [Array.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) over `cards` still relies on the sorted order.
This method works because the gap between two cards is never less than 10%.
Writing out a an example:
* Say the average is 2.2
* 2.2 * 0.9 = 1.98
* Doing the `find` over the array, the first card that's bigger than 1.98 is 2 - so that's what we use for concensus.

**Comment by xeronimus** [comment]
"This method works because the gap between two cards is never less than 10%."

Keep in mind, that we don't have control over the card values, since users can customize these...  Although I do not expect users to specify card values that are really close (1.1   1.2   1.3) - we should not knowingly implement an algorithm that fails in edge cases...

**Comment by xeronimus** [comment]
while implementing I noticed something, and I'd like your input :

currently the group is "motivated" to start a new round, if the "spread" of values is large.

e.g.  people  estimated 3  and others estimated 34. you cannot (currently) settle for a card "in between". 
you can only settle for cards, that were estimated at least by one person.
I'm convinced, that the discussion is the most crucial part. (i.e. figure out, why people have a different understanding of the "complexity" or "size" of that story).

however, it might be cumbersome that the tool "forces" you to estimate again...

what do you think?

**Comment by ecaron** [comment]
I like that approach. It sounds smart to have the system strongly encourage the team to realize "we need to discuss & re-estimate", but still [begrudgingly] offer the option to take the 21.

**Comment by xeronimus** [comment]
deployed 0.12.0
