### ISSUE TITLE
New "UUID" names for rooms is restricting the usage for us

### ISSUE THREAD

**Issue by sebastianzillessen** [Zuehlke/poinz#48]
Hi there.

We are using Poinz in our customer project a lot and were used to links like 

http://poinz.herokuapp.com/ourBestRoom

With the update to the new Rooms bases on UUIDs this is not possible anymore. 

I understand the security aspect of this change, but are you planning any feature to support this again?

All the best, 
Sebastian

**Comment by xeronimus** [comment]
Does the "alias" feature meet your needs?  

Rooms are no longer created on the fly. This means, since the heroku deployment will "sleep" when not used, rooms are lost.
Thus, wen accessing http://poinz.herokuapp.com/ourBestRoom (e.g. in the morning), you will end up on the landing page.

But, if you create a new room with the alias /ourBestRoom (click the "extend down" button on the landing page),  the room can directly be joined with   http://poinz.herokuapp.com/ourBestRoom by your team mates...

**Comment by xeronimus** [comment]
on second thought.. we could "restore" the previous behaviour by reinstating persistent storage. (There was a working redis store implementatione once...) So your room (with custom alias) would be persisted across application server restarts.. 

I would have to check whether I could pack redis into our docker image.. (remember, we are still running on a free tier heroku dyno ;) )

**Comment by xeronimus** [comment]
@sebastianzillessen  I deployed persistent storage (see #50 ) your rooms should now "survive the night" ;)

what about the alias feature ? could you  provide me with some feedback whether this is resolved for you?

**Comment by sebastianzillessen** [comment]
@xeronimus : Yes, the alias Feature is exactly what we were looking for and it works allright now for us. Looking into the persistent storage now :) 

Thanks a lot!
